// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsjZReOSrK2OGmMxdYhVclshIiliEwxA',
    appId: '1:738276536371:web:27586fa5c5e17c4158f346',
    messagingSenderId: '738276536371',
    projectId: 'fov-calendar-3bc2d',
    authDomain: 'fov-calendar-3bc2d.firebaseapp.com',
    storageBucket: 'fov-calendar-3bc2d.appspot.com',
    measurementId: 'G-NJQL1ZM3XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHa9C04j98qNrlHVS7vJUYCucYwUDR_4',
    appId: '1:738276536371:android:4ec5c74409c68d9058f346',
    messagingSenderId: '738276536371',
    projectId: 'fov-calendar-3bc2d',
    storageBucket: 'fov-calendar-3bc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQ_RODdq314hgTRYHj49P739E0YsZxpM',
    appId: '1:738276536371:ios:b1f50751b788be7958f346',
    messagingSenderId: '738276536371',
    projectId: 'fov-calendar-3bc2d',
    storageBucket: 'fov-calendar-3bc2d.appspot.com',
    iosBundleId: 'com.fedorvladysh.urnik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQ_RODdq314hgTRYHj49P739E0YsZxpM',
    appId: '1:738276536371:ios:b1f50751b788be7958f346',
    messagingSenderId: '738276536371',
    projectId: 'fov-calendar-3bc2d',
    storageBucket: 'fov-calendar-3bc2d.appspot.com',
    iosBundleId: 'com.fedorvladysh.urnik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXsjZReOSrK2OGmMxdYhVclshIiliEwxA',
    appId: '1:738276536371:web:73c801346ece2a0d58f346',
    messagingSenderId: '738276536371',
    projectId: 'fov-calendar-3bc2d',
    authDomain: 'fov-calendar-3bc2d.firebaseapp.com',
    storageBucket: 'fov-calendar-3bc2d.appspot.com',
    measurementId: 'G-FG0N3YMZV9',
  );
}
